name: ci

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic_pull_request:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      config: cspell.json
      includes: |
        **/*.{dart,md,yaml}
        !.dart_tool/**/*.{dart,yaml}
        .*/**/*.yml
      modified_files_only: false
  
  packages:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read

    outputs:
      packages: ${{ steps.packages.outputs.changes }}

    steps:
      - uses: dorny/paths-filter@v2
        id: packages
        with:
          filters: |
            goose:
              - ./.github/workflows/main.yaml
              - packages/goose/**

  build:
    needs: packages
    if: ${{ needs.packages.outputs.packages != '[]' }}

    strategy:
      matrix:
        package: ${{ fromJSON(needs.packages.outputs.packages) }}

    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      working_directory: packages/${{ matrix.package }}

